Repository rbzgamer/Morchor-s-Map, pull requests merged in 2024-02, with the labels that each got.

#12 Qaizx/route function
  front-end/morchor-map/package-lock.json
  front-end/morchor-map/package.json
  front-end/morchor-map/src/App.css
  front-end/morchor-map/src/App.js
  front-end/morchor-map/src/Components/map/Directions.js
  front-end/morchor-map/src/Components/map/Map.js
  front-end/morchor-map/src/Components/map/Navbar/DirectionBar.js
  front-end/morchor-map/src/Components/map/Navbar/Navbar.css
  front-end/morchor-map/src/Components/map/Navbar/Navbar.js
  front-end/morchor-map/src/Components/map/Navbar/building/Building.js
  front-end/morchor-map/src/Components/map/Navbar/faculty/Faculty.js
  front-end/morchor-map/src/Components/map/Navbar/room/Room.js
  front-end/morchor-map/src/Components/map/Navbar/searching/Search.js
Labels: bug, documentation, enhancement

#13 Responsive And Decorate
  front-end/morchor-map/.gitignore
  front-end/morchor-map/package-lock.json
  front-end/morchor-map/package.json
  front-end/morchor-map/src/App.css
  front-end/morchor-map/src/App.js
  front-end/morchor-map/src/Components/map/Directions.js
  front-end/morchor-map/src/Components/map/Map.js
  front-end/morchor-map/src/Components/map/Navbar/DirectionBar.js
  front-end/morchor-map/src/Components/map/Navbar/Navbar.css
  front-end/morchor-map/src/Components/map/Navbar/Navbar.js
  front-end/morchor-map/src/Components/map/Navbar/building/Building.css
  front-end/morchor-map/src/Components/map/Navbar/building/Building.js
  front-end/morchor-map/src/Components/map/Navbar/faculty/Faculty.js
  front-end/morchor-map/src/Components/map/Navbar/room/Room.js
  front-end/morchor-map/src/Components/map/Navbar/searching/Search.js
Labels: bug, documentation, enhancement

#14 finish show distance and duration
  front-end/morchor-map/src/App.js
  front-end/morchor-map/src/Components/map/Directions.js
  front-end/morchor-map/src/Components/map/Navbar/Navbar.js
  front-end/morchor-map/src/Components/map/Navbar/ShowDirectionInfo.js
Labels: enhancement

#15 fix route
  front-end/morchor-map/src/Components/map/Directions.js
Labels: bug

#16 Backend Google Maps API
  .gitignore
  back-end/morchor-map/.gitignore
  back-end/morchor-map/package-lock.json
  back-end/morchor-map/package.json
  back-end/morchor-map/src/app.module.ts
  back-end/morchor-map/src/location/controllers/location.controller.ts
  back-end/morchor-map/src/location/dto/RoutingLocation.dto.ts
  back-end/morchor-map/src/location/model/location.model.ts
  back-end/morchor-map/src/location/services/location.service.ts
Labels: enhancement
